server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:6336
          predicates:
          - Path=${app.api-prefix}/identity/**
          filters:
          - StripPrefix=2
        - id: profile_service
          uri: http://localhost:6366
          predicates:
          - Path=${app.api-prefix}/profile/users/**
          filters:
          - StripPrefix=2
        - id: notification_service
          uri: http://localhost:6666
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: product_service
          uri: http://localhost:6677
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2
        - id: order_service
          uri: http://localhost:6633
          predicates:
            - Path=${app.api-prefix}/order/**
          filters:
            - StripPrefix=2
        - id: review_service
          uri: http://localhost:6663
          predicates:
            - Path=${app.api-prefix}/review/**
          filters:
            - StripPrefix=2
        - id: cart_service
          uri: http://localhost:6368
          predicates:
            - Path=${app.api-prefix}/cart/**
          filters:
            - StripPrefix=2