server:
  port: 6677
  servlet:
    context-path: /product
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/product-service?authSource=admin
